<?php 
$_helper = $this->helper('googletagmanager');
$_containerId = trim($_helper->getContainerId()); 
if ($_helper->getIsEnable()): 
?>
	<!-- Google Tag Manager -->			
	
	<?php 
	if ($_helper->getIsEnableDataLayer()):
		echo $this->getDataLayerProduct();	// Product Detail Page	
		echo $this->getDataLayerOrder(); // Order Success Page
	endif;
	?>	
		
	<noscript><iframe src="//www.googletagmanager.com/ns.html?id=<?php echo $_containerId ?>"
	height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','<?php echo $_containerId ?>');</script>
	
	<!-- End Google Tag Manager -->
		
<?php endif; ?>
