<?php 
$_helper = $this->helper('googletagmanager');
$_containerId = trim($_helper->getContainerId()); 
if ($_helper->getIsEnable()): 
?>

<!-- Start Google Tag Manager -->		
	<noscript><iframe src="//www.googletagmanager.com/ns.html?id=<?php echo $_containerId ?>"
	height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>	
<!-- End Google Tag Manager -->		

<?php endif; ?>
